const en = {
  common: {
    fortrust: "FuChuang Information Technology (Chengdu) Co., Ltd.",
    systemName: "Microgrid Energy Service System",
    querySearch: "Search",
    queryReset: "Reset",
    queryDownload: "Export",
    queryInputPlhd: "Please enter {name}",
    querySelectPlhd: "Please select {name}",
    confirm: "Confirm",
    cancel: "Cancel",
    save: "Save",
    saveSuccess: "Save success",
    saveFailure: "Save failure",
    remove: "Remove",
    weekMap: [
      "Sunday",
      "Monday",
      "Tuesday",
      "Wednesday",
      "Thursday",
      "Friday",
      "Saturday",
    ],
    index: "Index",
    download: "Export data",
    dataLoading: "Data acquisition in progress...",
    chartRendering: "Chart rendering in progress...",
    paramsLoading: "Parameter acquisition in progress...",
    datetimePlaceholder: ["Select start time", "Select end time", "To"],
    operationTips: [
      "Tip",
      "Confirm",
      "Cancel",
      "Cancel Operation",
      "Delete successfully",
    ],
    close: "Close",
    totalPower: "gross power",
    phaseCurrent: "phase current",
    phaseVoltage: "phase voltage",
    generatedEnergy: "generated energy",
    add: "Add",
    commonNormal: "normal",
    commonOverCurrent: "over current",
    day: ["day", "days"],
  },
  login: {
    formLabel: ["Company ID", "User name", "Login password"],
    loginBtn: "Login",
  },
  menuBtn: {
    runningRecord: "Running records",
    historyCurve: "Historical curve",
    alarmRecord: "Alarm records",
  },
  // 运行记录
  runningRecord: {
    searchLabel: [
      "Keyword search for support device name/number",
      "Running time",
    ],
    tip: [
      "Photovoltaic and energy storage battery take power continuous not equal to 0 as running records; ",
      "Fan running records include standby (rotation number continuous not equal to 0, power is 0) and power generation (power continuous not equal to 0) two cases;",
    ],
    showCurve: "View curve",
    fileName: "Running records",
    columns: [
      "Index",
      "Running Equipment",
      "Equipment Number",
      "Start Time",
      "End Time",
      "Running Duration",
      "Generated Electricity",
      "Operation",
    ],
  },
  //历史曲线
  historyCurve: {
    model: ["List mode", "Curve mode"],
    searchParams: [
      "Select data",
      "Selected parameters",
      "Available parameters",
      "Reserve",
    ],
    searchTime: "Select time",
    searchResolution: [
      "Data resolution",
      "Select data resolution",
      "The lower the data resolution, the denser the curve, and the slower the query time may become. Please wait patiently.",
    ],
    dataTime: ["Data Time"],
  },
  // 报警记录
  alarmRecord: {
    searchLabel: ["Filter", "Type"],
    typeEnum: ["All", "Warning", "Shutdown"],
    columns: ["Content", "Type", "Start Time", "End Time"],
    categoryEnum: ["Site Alarm"],
  },
  // 微电网
  microgrids: {
    systemType: [
      "Power generation unit system",
      "Energy storage system",
      "Photovoltaic system",
      "Wind power system",
      "Grid",
    ],
    systemDrawerType: [
      "Power generation unit",
      "Energy storage battery",
      "Photovoltaic",
      "Wind power",
      "Grid",
      "Load",
    ],
    systemCard: {
      baseItems: ["Installed power", "Installed capacity", "Rated capacity"],
      chargeItems: [
        "Today's charging",
        "Today's discharging",
        "This month's charging",
        "This month's discharging",
      ],
      gridItems: [
        "Today's off-grid",
        "Today's on-grid",
        "This month's off-grid",
        "This month's on-grid",
      ],
      electricityGeneration: [
        "Today's power generation",
        "This month's power generation",
      ],
      tagItems: ["Battery level", "Battery health"],
      alert: "Current alarm",
      maintenance: "Maintenance plan",
      communication: "Communication status",
      communicationDes: ["Not yet due", "Due"],
    },
    LoadFeature: {
      title: "Load characteristics",
      timeInterval: "Power resolution",
      legend: [
        "Load",
        "Grid standby",
        "Energy storage standby",
        "Power generation unit standby",
      ],
    },
    OperationStrategy: {
      title: "Operation strategy",
      legend: [
        "Unit power generation",
        "Energy storage charging and discharging",
        "Photovoltaic power generation",
        "Wind power generation",
        "Grid up and down",
        "Load curve",
      ],
      toolTip: [
        "Grid down",
        "Grid up",
        "Energy storage discharge",
        "Energy storage charging",
      ],
    },
    ElectricEnergy: {
      title: "Electric energy operation diagram",
      alertTypes: [
        "Power generation unit system",
        "Energy storage system",
        "Photovoltaic system",
        "Wind power system",
        "Grid",
        "Load",
        "Charging pile",
      ],
      currentMode: "Current mode",
      modeList: ["Off-grid", "Grid-connected"],
      realTimeTotalPower: "Real-time total power",
      equipmentData: [
        "Mains electricity",
        "Photovoltaic",
        "Wind power",
        "Generator set",
        "Load",
        "Energy storage tank",
        "Charging pile",
      ],
      dataList: ["Power", "Line voltage", "current", "voltage"],
    },
    WeatherMonitor: {
      title: "Meteorological environment monitoring",
      dataItems: [
        "Irradiation",
        "Wind speed",
        "Air temperature",
        "Humidity",
        "Wind direction",
      ],
    },
    EconomicPerformance: {
      title: "Electricity income",
      changeTabs: ["Hour by hour", "Day by day"],
      systemList: [
        "Microgrid",
        "Energy storage subsystem",
        "Photovoltaic subsystem",
        "Wind power subsystem",
        "Generator set subsystem",
      ],
      helpDescribeList: [
        "Microgrid power generation revenue = Energy storage subsystem power generation revenue + Photovoltaic subsystem power generation revenue + Wind power subsystem power generation revenue + Generator unit subsystem revenue",
        "Photovoltaic power generation revenue = Time-sharing power generation capacity * Grid-connected time-sharing electricity price + Time-sharing power generation capacity * Time-sharing subsidy electricity price",
        "Energy storage power generation revenue = Time-sharing discharge power generation capacity * Discharging time grid-connected time-sharing electricity price - Time-sharing charging power generation capacity * Charging time grid-connected time-sharing electricity price",
        "Wind power generation revenue = Time-sharing power generation capacity * Grid-connected time-sharing electricity price + Time-sharing power generation capacity * Time-sharing subsidy electricity price",
        "Generator unit power generation revenue = Time-sharing power generation capacity x (Grid-connected time-sharing electricity price - Generator unit energy consumption electricity price cost)",
      ],
      dataItems: [
        "Earnings of the day",
        "Earnings of the month",
        "Earnings for the year",
        "Total Earnings",
      ],
      units: ["RMB"],
    },
  },
  // 参数配置
  configParams: {
    dataTime: "Cloud Data Time",
    statusEnum: [
      "Writing",
      "Reading",
      "Success",
      "Read Failed",
      "Write Failed",
    ],
    title: "Parameter configuration",
    read: "read",
    refresh: "refresh",
    operation: "tuning parameter",
    write: "write",
    checkRecord: "View the tuning records",
  },
  // 储能柜
  energyStorage: {
    title: "Energy storage power system monitor",
    tabs: [
      "Energy Storage Cabinet Overview",
      "PCS Management",
      "BMS Management",
    ],
    systemOverview: {
      titles: [
        "Real-time Data",
        "Air Conditioning and Firefighting",
        "Remote Control",
        "Main Configuration Parameters",
        "Electricity and SOC Curve",
        "Power Curve",
      ],
      modeEnum: ["Off-grid", "Grid-connected"],
      workStatusEnum: ["Shutdown", "Running", "Standby"],
      batteryStatusEnum: ["Charging", "Discharging", "Standby"],
      realDataItems: {
        0: "Installed Power/Capacity",
        1: [
          "Current Mode",
          "Work Status",
          "Remaining Electricity SOC",
          "Battery Health SOH",
        ],
        2: [
          "Fault",
          "Alarm",
          "Failure",
          "Derating",
          "Starting",
          "Equalization",
          "Lowering",
        ],
        4: [
          "DC Power",
          "Power Factor",
          "Reactive Power",
          "Grid Frequency",
          "Active Power",
          "Battery Voltage",
          "Battery Current",
          "Battery Max Temperature",
          "Battery Min Temperature",
          "Battery Average Temperature",
          "PCS Temperature",
        ],
      },
      fireDataItems: {
        0: [
          "Operation Mode",
          "Operation Status",
          "Air Conditioning Status",
          "Indoor Temperature",
          "Indoor Humidity",
          "Outdoor Temperature",
          "CO Content",
          "CO2 Concentration",
          "PM2.5 Concentration",
          "Temperature",
          "Bottle Group Pressure",
        ],
        runModeEnum: [
          "Automatic",
          "Forced Cooling",
          "Forced Heating",
          "Forced Air Supply",
          "Standby",
        ],
        runStatusEnum: ["On", "Off"],
        airStatusEnum: ["Normal", "Fault"],
      },
      controlDataItems: {
        btnLabels: ["Clear Fault", "Turn On", "Turn Off"],
        operationTips: [
          "Please ensure the site safety and full authorization from the equipment owner before operating",
          "The control command has been issued, please observe the page data changes to verify the control result",
        ],
      },
      configDataItems: [
        "Energy Scheduling Mode",
        "Control Mode",
        "Microgrid Power Supply Mode",
        "Power-on Startup Method",
        "Islanding Detection",
        "Microgrid PC Control Command",
        "Active Power Control Mode",
        "Reactive Power Control Mode",
      ],
      electricityDataItems: {
        labels: [
          "Today's Charge",
          "Today's Discharge",
          "This Month's Charge",
          "This Month's Discharge",
          "This Year's Charge",
          "This Year's Discharge",
          "Cumulative Charge",
          "Cumulative Discharge",
        ],
        legendLabels: [
          "Charging Electricity",
          "Discharging Electricity",
          "Remaining Electricity SOC",
        ],
      },
      powerDataItems: {
        legendLabels: ["Charging DC Power", "Discharging Active Power"],
      },
    },
    pcsManage: {
      titles: [
        "Status Information",
        "DC Side Data",
        "AC Side Data",
        "Device Parameter Configuration",
      ],
      realDataItems: {
        0: [
          "Installed Capacity",
          "Device Model",
          "Maintenance Plan",
          "Module Temperature",
          "Environmental Temperature",
          "cabin temperature",
        ],
      },
      statusDataItems: {
        systemStatus: "System is starting up...",
        statusEnum: [
          {
            label: "Charging/Discharging State",
            statusEnum: ["Charging", "Discharging"],
          },
          { label: "Fault State", statusEnum: ["Fault", "Normal"] },
          { label: "Alarm State", statusEnum: ["Alarm", "Normal"] },
          { label: "Failure State", statusEnum: ["No", "Yes"] },
          { label: "Full/Empty State", statusEnum: ["Full", "Empty"] },
          { label: "Equalization State", statusEnum: ["No", "Yes"] },
          { label: "Derating State", statusEnum: ["Derating", "Normal"] },
          { label: "Lowering State", statusEnum: ["No", "Yes"] },
          {
            label: "Grid Status",
            statusEnum: ["Reconnecting", "Recovery Delay"],
          },
          { label: "Electrical Room Fan Stopped", statusEnum: ["No", "Yes"] },
          { label: "AC Module 01 Online State", statusEnum: ["No", "Yes"] },
        ],
      },
      dcDataItems: {
        0: [
          "DC Power",
          "DC Voltage",
          "DC Current",
          "Cumulative Charging Energy",
          "Cumulative Discharging Energy",
        ],
      },
      acDataItems: {
        0: [
          "AC Rated Power",
          "Total Active Power",
          "Total Power Factor",
          "Total Reactive Power",
          "Total Apparent Power",
        ],
        1: ["A Phase", "B Phase", "C Phase"],
        2: ["Busbar Frequency", "Leakage Current"],
        3: [
          "Today's Charging Energy",
          "Today's Discharging Energy",
          "Cumulative Charging Energy",
          "Cumulative Discharging Energy",
        ],
        4: [
          "Busbar Phase Voltage Average",
          "Busbar AB Phase Difference",
          "Busbar BC Phase Difference",
          "Busbar AC Phase Difference",
        ],
        5: [
          "AC AB Phase Difference",
          "AC BC Phase Difference",
          "AC AC Phase Difference",
        ],
        6: ["AC Current I1a", "AC Current I1b", "AC Current I1c"],
        7: ["AC Current I2a", "AC Current I2b", "AC Current I2c"],
        8: [
          "AC Current Distortion Rate A",
          "AC Current Distortion Rate B",
          "AC Current Distortion Rate C",
        ],
        9: ["Running Time Accumulation", "Continuous Running Time"],
        10: [
          "Cumulative Active Power",
          "Cumulative Reactive Power",
          "Cumulative Charging Power",
        ],
      },
      configDataItems: {
        types: [
          "Basic Parameters",
          "Power Parameters",
          "Voltage and Current Parameters",
          "Protection Parameters",
          "Other Parameters",
        ],
        0: [
          "Energy Scheduling Mode",
          "Control Mode",
          "Microgrid Power Supply Mode",
          "Power-on Startup Method",
          "Microgrid PC Control Command",
          "Parallel Machine Communication Test",
          "Island Enable Test",
          "Grid Capacity Limit",
          "Grid Recovery Delay",
          "Voltage Frequency Crossing Mode",
          "Off-grid Voltage Startup Mode",
          "BMS Protocol Type",
        ],
        1: [
          "Power Change Mode",
          "Active Power Control Mode",
          "Active Power Setting",
          "Power Factor Setting",
          "A-phase Active Power Setting",
          "B-phase Active Power Setting",
          "C-phase Active Power Setting",
          "Reactive Power Control Mode",
          "Reactive Power Setting",
          "A-phase Reactive Power Setting",
          "B-phase Reactive Power Setting",
          "C-phase Reactive Power Setting",
          "Normal Power Change Rate",
          "Soft Start Power Change Rate",
        ],
        2: [
          "Off-grid AC Voltage Adjustment",
          "Off-grid AC Frequency Adjustment",
          "DC Lower Voltage Limit",
          "Discharge Terminal Voltage",
          "Equalization Voltage",
          "Maximum Charging Current",
          "Maximum Discharging Current",
        ],
        3: [
          "Overvoltage 1st Stage Protection Range",
          "Overvoltage 1st Stage Protection Delay",
          "Overvoltage 2nd Stage Protection Range",
          "Overvoltage 2nd Stage Protection Delay",
          "Undervoltage 1st Stage Protection Range",
          "Undervoltage 1st Stage Protection Delay",
          "Undervoltage 2nd Stage Protection Range",
          "Undervoltage 2nd Stage Protection Delay",
          "Overfrequency 1st Stage Protection Range",
          "Overfrequency 1st Stage Protection Delay",
          "Overfrequency 2nd Stage Protection Range",
          "Overfrequency 2nd Stage Protection Delay",
          "Underfrequency 1st Stage Protection Range",
          "Underfrequency 1st Stage Protection Delay",
          "Underfrequency 2nd Stage Protection Range",
          "Underfrequency 2nd Stage Protection Delay",
        ],
        4: [
          "Insulation Resistance Alarm Threshold",
          "Insulation Detection Function Definition",
          "Input Dry Contact A Custom Function",
          "Input Dry Contact B Custom Function",
          "Input Dry Contact C Custom Function",
          "Input Dry Contact D Custom Function",
          "Output Dry Contact A Custom Function",
        ],
      },
    },
    bmsManage: {
      titles: ["Battery Cluster", "Digital Signal", "BMS Parameter Setting"],
      realDataItems: {
        0: [
          "Remaining Battery Capacity SOC",
          "Battery Health SOH",
          "Total Current",
          "Total Voltage",
          "Insulation Resistance",
        ],
        1: [
          "Installed Power",
          "Installed Capacity",
          "Device Model",
          "Maintenance Plan",
        ],
        3: [
          "Battery Average Temperature",
          "Actual Temperature Collection Points",
          "Battery Maximum Temperature",
          "Maximum Temperature Module Number",
          "Maximum Temperature Collection Point",
          "Battery Minimum Temperature",
          "Minimum Temperature Module Number",
          "Minimum Temperature Collection Point",
        ],
        4: [
          "Cumulative Charging Electricity",
          "Cumulative Discharging Electricity",
          "Single Charging Electricity",
          "Single Discharging Electricity",
        ],
      },
      batteryDataItems: {
        types: ["Battery Pack", "Battery Module", "Single Cell"],
        0: [
          "Powerful Box Average Temperature",
          "Powerful Box Maximum Temperature",
          "Powerful Box Minimum Temperature",
          "Maximum Temperature Module Number",
          "Minimum Temperature Module Number",
          "Maximum Temperature Collection Point",
          "Minimum Temperature Collection Point",
        ],
        1: [
          "Battery Module Maximum Voltage",
          "Battery Module Minimum Voltage",
          "Maximum Voltage Sequence Number",
          "Minimum Voltage Sequence Number",
        ],
        2: ["Total Sections", "Average Voltage", "Average SOC", "Average SOH"],
        3: [
          "Maximum Single Cell Voltage",
          "Maximum Voltage Module Number",
          "Maximum Voltage Section Number",
          "Minimum Single Cell Voltage",
          "Minimum Voltage Module Number",
          "Minimum Voltage Section Number",
        ],
        4: [
          "Maximum Single Cell SOC",
          "Maximum SOC Module Number",
          "Maximum SOC Section Number",
          "Minimum Single Cell SOC",
          "Minimum SOC Module Number",
          "Minimum SOC Section Number",
        ],
        5: [
          "Maximum Single Cell SOH",
          "Maximum SOH Module Number",
          "Maximum SOH Section Number",
          "Minimum Single Cell SOH",
          "Minimum SOH Module Number",
          "Minimum SOH Section Number",
        ],
      },
      digitalSignal: {
        types: ["Input Signal", "Output Signal"],
        inputLabel: "{name} Input", // {name}为输入信号名称
        outputLabel: "{name} Output", // {name}为输出信号名称
      },
      configDataItems: {
        types: [
          "Temperature Alarm Parameter",
          "Voltage Alarm Parameter",
          "Current Alarm Parameter",
          "Other Parameters",
        ],
        0: [
          "Single Over-temperature 1st Level Alarm Threshold",
          "Single Over-temperature 2nd Level Alarm Threshold",
          "Single Over-temperature 3rd Level Alarm Threshold",
          "Battery Over-temperature Alarm Hysteresis",
          "Single Under-temperature 1st Level Alarm Threshold",
          "Single Under-temperature 2nd Level Alarm Threshold",
          "Single Under-temperature 3rd Level Alarm Threshold",
          "Battery Under-temperature Alarm Hysteresis",
          "Single Temperature Difference 1st Level Alarm Threshold",
          "Single Temperature Difference 2nd Level Alarm Threshold",
          "Single Temperature Difference 3rd Level Alarm Threshold",
          "Single Temperature Difference Alarm Hysteresis",
          "Power Connector Temperature High 1st Level Alarm Threshold",
          "Power Connector Temperature High 2nd Level Alarm Threshold",
          "Power Connector Temperature High 3rd Level Alarm Threshold",
          "Power Connector Temperature High Alarm Hysteresis",
        ],
        1: [
          "Group Over-voltage 1st Level Alarm Threshold",
          "Group Over-voltage 2nd Level Alarm Threshold",
          "Group Over-voltage 3rd Level Alarm Threshold",
          "Group Over-voltage Alarm Hysteresis",
          "Group Under-voltage 1st Level Alarm Threshold",
          "Group Under-voltage 2nd Level Alarm Threshold",
          "Group Under-voltage 3rd Level Alarm Threshold",
          "Group Under-voltage Alarm Hysteresis",
          "Single Over-voltage 1st Level Alarm Threshold",
          "Single Over-voltage 2nd Level Alarm Threshold",
          "Single Over-voltage 3rd Level Alarm Threshold",
          "Single Over-voltage Alarm Hysteresis",
          "Single Under-voltage 1st Level Alarm Threshold",
          "Single Under-voltage 2nd Level Alarm Threshold",
          "Single Under-voltage 3rd Level Alarm Threshold",
          "Single Under-voltage Alarm Hysteresis",
          "Single Voltage Difference 1st Level Alarm Threshold",
          "Single Voltage Difference 2nd Level Alarm Threshold",
          "Single Voltage Difference 3rd Level Alarm Threshold",
          "Single Voltage Difference Alarm Hysteresis",
          "Battery Module Over-voltage 1st Level Alarm Threshold",
          "Battery Module Over-voltage 2nd Level Alarm Threshold",
          "Battery Module Over-voltage 3rd Level Alarm Threshold",
          "Battery Module Over-voltage Alarm Hysteresis",
          "Battery Module Under-voltage 1st Level Alarm Threshold",
          "Battery Module Under-voltage 2nd Level Alarm Threshold",
          "Battery Module Under-voltage 3rd Level Alarm Threshold",
          "Battery Module Under-voltage Alarm Hysteresis",
        ],
        2: [
          "Group Discharge Over-current 1st Level Alarm Threshold",
          "Group Discharge Over-current 2nd Level Alarm Threshold",
          "Group Discharge Over-current 3rd Level Alarm Threshold",
          "Group Discharge Over-current Alarm Hysteresis",
          "Group Charge Over-current 1st Level Alarm Threshold",
          "Group Charge Over-current 2nd Level Alarm Threshold",
          "Group Charge Over-current 3rd Level Alarm Threshold",
          "Group Charge Over-current Alarm Hysteresis",
        ],
        3: [
          "SOC too low 1st Level Alarm Threshold",
          "SOC too low 2nd Level Alarm Threshold",
          "SOC too low 3rd Level Alarm Threshold",
          "SOC too low Alarm Hysteresis",
          "Group Insulation 1st Level Alarm Threshold",
          "Group Insulation 2nd Level Alarm Threshold",
          "Group Insulation 3rd Level Alarm Threshold",
          "Group Insulation Alarm Hysteresis",
        ],
      },
    },
  },
  // 维保设置
  maintenance: {
    title: ["Maintenance Management"],
    baseData: [
      "Cumulative running time",
      "Cumulative natural days",
      "Maintenance initialization date",
      "Maintenance initialization running time",
    ],
    baseDataTip: [
      "Default equipment delivery date (if none, the equipment first added to the system creation date)",
      "Default equipment delivery running time (first collected from EMS or calculated in the cloud, if none, default to 0)",
    ],
    tabs: ["Maintenance Plan", "Maintenance Strategy", "Maintenance Record"],
    showType: ["Interval style", "Accumulated styles"],
    operates: ["Strategy Adjustment", "Strategy Preservation"],
    types: ["First Maintenance", "Regular Maintenance"],
    status: ["Overdue without Maintenance", "To be maintained", "nodata"],
    strategy: {
      columns: ["Index", "Maintenance Items"],
      add: ["Add Maintenance Cycle", "Add Maintenance Items"],
      des: ["Running", "Or", "Natural Days"],
      tip: [
        "Please Add Maintenance Items!",
        "First maintenance or regular maintenance items are duplicated!",
        "Are you sure to delete the maintenance cycle?",
        "Are you sure to delete the maintenance item?",
        "The running time and natural day in the maintenance cycle cannot be empty!",
      ],
    },
    plan: {
      columns: [
        "Index",
        "Maintenance Item",
        "Status",
        "Maintenance Strategy",
        "Last Maintenance",
        "Maintenance Plan",
        "Days to Maintenance Plan",
        "Running Time to Maintenance Plan",
      ],
      statusMap: [
        "Pending Maintenance",
        "Overdue for Maintenance",
        "Soon Due for Maintenance",
      ],
    },
    record: {
      search: ["Maintenance Date"],
      title: "Record Details",
      labels: [
        "Maintenance Time",
        "Maintenance Address",
        "Accu. Running time of the Genset during Maintenance",
        "Accu. Natural Days of the Genset during Maintenance",
        "Maintenance Implementer",
        "Signature of Maintenance Implementer",
        "Submission Time",
        "Submitter",
      ],
      itemDetail: [
        "Maintenance Items",
        "Before Maintenance",
        "After Maintenance",
        "Maintenance Material Model",
      ],
      tips: ["No maintenance records found", "No maintenance details found"],
    },
    noMaintenanceTip: "Please configure the maintenance strategy first",
    describe: {
      des: ["or", "(first maintenance)", "none"],
      intervalDes: ["Run for {hour} hours", "Day {day}"],
      accumulatedDes: ["Run for {hour} hours per day", "Day {day}"],
      lastDes: ["Run for {hour} hours"],
      nextDes: ["Accumulated run for {hour} hours"],
      statusDes: [
        "Remaining {day} days",
        "Over {day} days",
        "Remaining {hour} hours",
        "Over {hour} hours",
      ],
      nextPlanDes: [
        "Has been running for more than {day} days",
        "Has been running for more than {hour} hours",
        "without maintenance",
        "{day} days left",
        "Will run for another {hour} hours",
      ],
    },
  },
  // 光伏子系统
  photovoltaic: {
    title: "Photovoltaic Power Generation System Monitoring",
    inverter: "photovoltaic inverter",
    systemStatusLabel: [
      "Standby",
      "self-checking",
      "grid-connected operation",
      "firmware upgrade",
      "fault",
      "debugging",
      "input detection",
      "not grid-connected operation",
    ],
    // autoStartUpRemainTime: 'Automatic boot the remaining time',
    autoStartUpRemainTime: "boot remaining ",
    paramsConfig: {
      title: "Main parameter configuration",
      configDataItems: [
        "Scheduling mode",
        "reactive power control mode",
        "Output active power scheduling power",
        "boot active load rate",
        "Output reactive power dispatching power",
        "active power scheduling change rate",
      ],
    },
    control: {
      title:
        "Please ensure the safety of the site before operation, and fully authorized by the person responsible for the equipment",
      successMes:
        "Control instructions have been issued, please observe the page data changes to verify the control results",
    },
    powerStatistic: [
      "Power generation statistics ",
      " today",
      " month",
      " year",
      " generation",
    ],
    settingDialog: {
      title: "The relationship between MPPT and PV is set",
    },
  },
  // 风能子系统
  wind: {
    title: "Wind Power Generation System Monitoring",
    cloudCrew: "wind turbine crew",
    startUpWindSpeed: "cut-in wind speed",
    statusEnum: [
      {
        label: "temperature ",
        statusEnum: ["normal", "over-temperature protection"],
      },
      { label: "Fan cut in", statusEnum: ["cut in", "no cut in"] },
      {
        label: "brake ",
        statusEnum: ["stop brake in place", "brake release in place"],
      },
      { label: "grid smoke", statusEnum: ["normal", "over-voltage"] },
      { label: " frequency", statusEnum: ["normal", "over-frequency"] },
    ],
    machineLabels: {
      1: "Fan power",
      2: "Fan speed",
      3: "Fan voltage",
      4: "Fan current",
    },
    paramsConfig: {
      configDataItems: [
        "Maximum grid-connected output set power",
        "Fan controller communication address",
      ],
    },
  },
  inverter: {
    mainVol: "bus voltage",
    commercialFrequency: "commercial frequency",
    inverterCurrent: " inverter output current",
    inverterVoltage: "inverter output voltage",
    inverterPower: " Inverter Power",
  },
};
module.exports = en;
