const en = {
  ele: {
    confirm: "确 定",
    cancel: "取 消",
    cancelled: "已取消",
    inputPlaceholder: "请输入",
    selectPlaceholder: "请选择",
  },
  common: {
    notHandle: "untreated",
    toBeDealt: "Follow up",
    inProcess: "Processing",
    submit: "submit",
    back: "Back",
    backHome: "Back to home page",
    logout: "退出",
    fullscreen: "Full screen",
    close: "Turn off",
    saveAddBack: "Save and return",
    add: "add",
    added: "Already add",
    select: "Seleced",
    remove: "Remove",
    restore: "Renew",
    save: "save",
    edit: "edit",
    delete: "delete",
    cancel: "Cancel",
    show: "Check",
    search: "search",
    reset: "reset",
    screening: "Filter",
    clear: "Clear filter",
    query: "查询",
    newAdd: "新建",
    noData: "No data available",
    sureToClose: "Confirm close",
    loadingText: "Data loading...",
    loadingText2: "Data loading, please wait...",
    loadingText3: "The map is loading, please wait...",
    all: "All",
    gensetStatus: ["Run", "Fault", "Warning", "Stop", "Offline", "All"],
    startDatePlaceholder: "Start date",
    endDatePlaceholder: "End date",
    startTimePlaceholder: "Start time",
    endTimePlaceholder: "End time",
    to: "to",
    selectDate: "Select date",
    selectDateTime: "Select date time",
    index: "Serial No.",
    operate: "operation",
    meter: "meter.",
    latitude: "latitude",
    longitude: "longitude",
    refresh: "Click Refresh page",
    day: ["天", "天"],
    willExpire: "天后到期",
    expired: "Have expired",
    operateTip: "Operation prompt",
    operateTipResMsg: "operation success",
    tip: "Tips",
    tipContent: "Need to retrieve the data again?",
    tipResMsg: "重新获取数据成功!",
    deleteTip: "Delete prompt",
    deleteTipContent: [
      "This operation will cause data to be unrecoverable, please operate with caution!",
      "Are you sure you want to delete the data?",
    ],
    deleteTipResMsg: ["Deleted successfully!", "Delete failed!", "undeleted"],
    yes: "Yes",
    no: "No",
    imagePreview: "Picture preview",
    download: "Download",
    preview: "Preview",
    downloadTemplate: "Download stencil",
    downloadFile: "Download file",
    engine: "Engine",
    generator: "Generator",
    generator0: "Power generation",
    shi_dian: "Mains",
    load: "Load",
    phaseVoltage: "Phase voltage",
    lineVoltage: "Line voltage",
    ADCVoltage: "ADC voltage",
    altitude: "Altitude",
    altitude0: "Altitude",
    temperature: "Temperature",
    windage: "Wind drag",
    chargeVoltage: "Charger voltage",
    runTime: "Run time",
    absoluteTime: "Absolute time",
    engineOilTemperature: "Oil Temperature",
    hour: "小时",
    hour0: "时",
    minute: "分钟",
    minute0: "分",
    second: "秒",
    second0: "秒",
    millisecond: "毫秒",
    unknown: "未知",
    unit: "unit",
    power: "功率",
    time: "时间",
    speed: "转速",
    quantity: "数量",
    refresh0: "刷新",
    readData: "读取",
    enable: "启用",
    disable: "禁用",
    write: "写入",
  },
  reliabilityEnum: [
    "Not classified",
    "Main unitA-3",
    "Main unitA-2",
    "Main unitA-1",
    "Main unitA-0",
    "Peaking unitB-3",
    "Peaking unitB-2",
    "Peaking unitB-1",
    "Peaking unitB-0",
    "Standby unitC",
    "Standby unitC",
    "Standby unitC",
    "Standby unitC",
  ],
  login: {
    title: "Intelligent Equipment Power Service Rental Platform",
    customerPlaceholder: "Please enter the company ID",
    userNamePlaceholder: "Please enter your username",
    passwordPlaceholder: "请输入密码",
    loginBtn: "登 录",
  },
  menu: {
    monitoringScreenTitle: "home page",
    gensetGroupMonitorTitle: "Genset group monitoring",
    project: {
      projectManageTitle: "project management",
      projectListTitle: "project list",
      projectMonitorTitle: "project monitoring",
      projectDetailTitle: "project details",
      projectGensetTitle: "project gensets",
      controllerConfigurationTitle: "Controller configuration",
      projectMonitorTitleOld: "项目监控-旧",
      engineeringManagementTitle: "engineering management",
      completionRecordTitle: "Completion Record",
      projectProgressRecordTitle: "Project Engineering Progress",
      gensetProgressRecordTitle: "Single engine engineering progress",
    },
    equipment: {
      equipmentManageTitle: "Device management",
      crewinfoTitle: "Genset information",
      crewinfoDetailTitle: "Genset information details",
      crewinfoConfigTitle: "Genset configuration",
      crewreportTitle: "Genset report",
      crewreportDetailTitle: "Check report details",
      crewDistributeTitle: "Genset distribution",
      crewmonitorTitle: "Genset monitoring",
      crewLocationTitle: "Genset anti-theft",
      crewTrackTitle: "Genset track",
      dataRecordTitle: "Data record",
      handleRecordTitle: "Operation records",
      alarmCurveRecordTitle: "Alarm curve recording",
      oneclickRepairRecordTitle: "One click repair record",
      startingCurveRecordTitle: "Start curve recording",
      CurveReportTitle: "Check curve details",
      runningRecordTitle: "Operation records",
      alarmHistoryTitle: "Alarm history",
      onlineRecordTitle: "Online Record",
      generationEnergyStatisticsTitle: "Power generating calculation",
      historicalCurveTitle: "历史曲线",
      fuelRecordTitle: "燃油记录",
      historyRecordTitle: "History Data",
      crewHistoryRecordTitle: "Genset Resume",
      fixedAssertsTitle: "固定资产管理",
    },
    operation: {
      operationManageTitle: "运维管理",
      remoteTuningTitle: "Remote configuration",
      remoteTuningHistoryTitle: "远程调参-调参历史",
      remoteTuningOperationTitle: "远程调参-调参操作",
      deteriorationAnalysisTitle: "Degradation Analysis",
      leaseGensetTitle: "租赁机组",
      crewCloudTitle: "Cloud Service",
      maintenanceMonitorTitle: "维保监控",
      powerQualityMonitoringTitle: "电能质量监控",
      userFeedbackTitle: "用户反馈",
      userFeedbackDetailTitle: "工单详情",
      operationalChartTitle: "运维图",
      operationalChartDailyTitle: "日运维图",
      operationalChartWeeklyTitle: "周运维图",
      gensetLockTitle: "Remote unlock",
      cloudMessagePushTitle: "Send Cloud message",
    },
    resource: {
      resourceManageTitle: "资源管理",
      servicesProvidersManageTitle: "服务商管理",
      sparePartsManageTitle: "备件管理",
    },
    setting: {
      settingTitle: "系统设置",
      agreementManageTitle: "协议管理",
      maintenanceStrategyTitle: "维保策略",
      maintenanceStrategyAddTitle: "新增维保策略",
      maintenanceStrategyShowTitle: "查看维保策略",
      authManageTitle: "权限管理",
      organizationalStructureTitle: "组织架构管理",
      usersManageTitle: "人员管理",
      functionalAuthTitle: "功能权限管理",
      dataAuthTitle: "数据权限管理",
      advertisementManageTitle: "广告位管理",
      advertisementAppTitle: "app端广告位",
      advertisementAppletTitle: "小程序广告位",
    },
  },
  crewList: {
    searchListPlaceholder: ["Please select a project", "Input Generator Name"],
  },
  layout: {
    realTimeMonitoring: {
      title: "实时监控",
      drawerTitle: "实时监控事项",
      items: ["运行报警", "周期维保", "环境风险", "自动维保"],
      statusItems: ["Warning", "Fault", "维保"],
      remark: "备注",
      FpieRemindKey1: "自动补换机油周期情况",
    },
    helpCenter: {
      title: "Help center",
      tip: "Click to open the Help Center",
      addWord: "Add new document",
      editWord: "Edit document",
      deleteWord: "delete",
      deleteConfirmTip: "Do you want to delete the document?",
      deleteResponseTip: "This document has been deleted",
      onShelf: "listing",
      onShelfConfirmTip: "Do you want to upload this document?",
      onShelfResponseTip: "The document is available",
      offShelf: "delist",
      offShelfConfirmTip: "Do you want to remove the document?",
      offShelfResponseTip: "This document has been removed",
      des: "There is no help document on the current page, please add a document",
      belongPage: "Owning page",
      belongPageTip: "Please select a page",
      name: "Document name",
      nameTip: "Please fill in the document name",
      namePlaceholder: "请输入十字以内标题",
      content: "Document content",
      contentTip: "Please fill in the document",
      submitTip: "Submit successfully",
      saveResponseTip: "The document title already exists, please check!",
    },
    AccountSetting: {
      title: "Account information",
      settingTitle: "Account setting",
      infoItems: ["department", "本次登录", "Landing area", "上次登录"],
      userName: "username",
      userNamePlaceholder: "Please enter your username",
      oldPassword: "Old password",
      oldPasswordPlaceholder: "Please enter the old password",
      newPassword: "New password",
      newPasswordPlaceholder: "Please enter your new password",
      passwordTip: "6 to 8 characters in length",
      confirmPassword: "Confirm password",
      confirmPasswordPlaceholder: "Please enter your new password again",
      confirmPasswordTip: "The two passwords are different",
    },
  },
  monitoringScreen: {
    project: {
      allTitle: "Project Overview",
      totalLabel: "Genset Number",
      operateTotalLabel: "O&M Genset Number",
      helpOperateTotalLabel: "Outsourced O&M Genset Number",
      totalProjectLabel: "Project Number",
      projectConstructTitle: "Project Architecture",
      projectConstructDetail: "Architecture details",
    },
    genset: {
      status: "Genset status",
      operateStatusList: ["Run", "Fault", "Risky", "Stop", "Offline"],
      rentingStatusList: ["维保", "Renting", "Construct", "For Rent", "Repair"],
    },
    map: {
      mapTypeList: [
        "Global radiation map of intelligent equipment",
        "Chinese distribution map of intelligent equipment",
      ],
      tipTitleList: [
        "Click to return to the global radiation map of intelligent equipment",
        "Click to restore the initial state",
        "Click to display the map in full screen",
      ],
      chart: {
        gensetType: "Genset classification",
        gensetStatus: "Operating status of leased Gensets",
        typeList1: [
          "For Rent",
          "Renting",
          "Construct",
          "Maintenance",
          "Repair",
        ],
        typeList2: ["Normal", "Fault", "Risky", "Stop", "Offline"],
        tipList: [
          "Auto broadcast paused",
          "Auto broadcast started",
          "S后将自动展示智能装备中国分布图",
          "已停止自动展播",
          "点击开始自动展播",
          "点击暂停展播",
        ],
        clickToNation: "点击立即跳转",
      },
      curve: {
        title: "全球智能装备数量Top10",
        title2pre: "Provinces of China",
        title2back: "智能装备数量Top15",
        dialogTitle: "数据详情",
      },
      chartNation: {
        genSetStateOperationMapName: [
          "Offline",
          "Stop",
          "Risky",
          "Fault",
          "Run",
        ],
        genSetStateRentingMapName: [
          "待租",
          "Renting",
          "Repair",
          "Construct",
          "维保",
        ],
        genSetTimelineLabelMapping: [
          "All",
          "For Rent",
          "Construct",
          "Renting",
          "维保",
          "Repair",
        ],
        labelBelongToProject: "所属项目",
      },
    },
    feedback: {
      title: "客户反馈",
      allFeedback: "全部反馈",
      clickToCheckDetail: "Click for details",
      dialogTitle: "Customer feedback Details",
      dialogSend: "send",
      dialogPlaceholder: "No more than 100 characters",
      dialogText: "text",
      dialogPhoto: "picture",
    },
    bottomTable: {
      titleList: [
        "维保提示与报警实时监控",
        "设备与报警实时监控",
        "环境风险提示与报警实时监控",
      ],
      statusList: ["待受理", "Processing", "Done"],
      hoverTitleList: [
        'Click to switch to the "Maintenance monitoring" page',
        'Click to jump to the "Project monitoring" page',
        'Click to jump to the "Unit monitoring" page',
      ],
    },
  },
  project: {
    typeEnum: ["运维", "Managed operation and maintenance"],
    statusEnum: ["准备中", "Processing", "Done"],
    fileTypeEnum: ["合同", "聊天截图", "行程单"],
    warningDataTitle: ["实时报警", "Maintenance Alert"],
    list: {
      searchForm: {
        projectName: "Project name",
        projectNamePlaceholder: "Please enter a project name",
        projectType: "Item type",
        projectTypePlaceholder: "Please select the project type",
        projectStatus: "Project status",
        projectStatusPlaceholder: "Please select project status",
        position: "项目地址",
        effectTime: "项目生效时间",
        creatTime: "项目创建时间",
      },
      tableColumns: [
        "Project name",
        "Item type",
        "项目编号",
        "功率需求",
        "机组数量",
        "项目地址",
        "项目创建时间",
        "Project status",
        "项目开始时间",
        "项目结束时间",
        "到期剩余时间",
      ],
      addNewProject: "New project",
      expire: "Expiring item",
      open: "Open project",
      close: "Completed project",
      openProjectTip: "确定开启项目 XX 吗？",
      openProjectTip2:
        "The enable operation cannot be canceled.  Exercise caution when performing this operation.",
      closeProjectTip: "确定完结项目吗？",
      closeProjectTip2:
        "完结后，项目相关信息将不再支持编辑，操作不可取消，请谨慎操作。",
    },
    mouldPage: {
      listTitle: [
        "项目信息",
        "project gensets",
        "项目监控(新)",
        "project monitoring",
        "engineering management",
        "Completion Record",
        "Data record",
      ],
      selectProject: "选择项目",
      noDataTip: "当前项目状态下无项目数据",
      projectList: "project list",
      projectListPlaceholder: "请选择项目",
      changeProject: "切换项目",
      infoItems: [
        "项目机组功率（kW）",
        "项目机组数量（台）",
        "项目创建时间",
        "项目地址",
      ],
    },
    ItemTitles: [
      "基本信息",
      "参数配置",
      "合同文件",
      "项目人员",
      "project gensets",
      "机组群设置",
      "并机组配置",
    ],
    operateTitle: ["New item", "Edit item"],
    operateResTip: [
      "New project success!",
      "New project failed, please resubmit!",
      "Edit project successful!",
      "Edit project failed, please resubmit!",
    ],
    projectForm: [
      "Project name",
      "项目编号",
      "Item type",
      "项目地址",
      "项目起止时间",
      "功率需求",
      "租赁台数",
      "项目租金",
      "创建时间",
      "合同状态",
    ],
    formTip: ["China", "global", "-", "RMB", "条"],
    projectFormPlaceholder: [
      "Please enter a project name",
      "Please enter the project number",
      "Please select the project type",
      "Please enter the full address",
      "",
      "Please enter project power requirements",
      "Please enter the number of rental units",
      "Please enter the project rent",
    ],
    projectFormRules: [
      { required: "请输入项目名称", reg: "长度不超过 15 个字符" },
      { required: "请输入项目编号", reg: "长度不超过 20 个字符" },
      { required: "请选择项目类型", reg: "" },
      { required: "请选择项目地址", reg: "" },
      { required: "请选择项目起止时间", reg: "" },
      {
        required: "请输入功率需求",
        reg: "限制整数位不超过6位,小数点不超过2位",
      },
      { required: "请输入租赁台数", reg: "仅可输入不超过两位数的非零正整数" },
      {
        required: "请输入项目租金",
        reg: "限制整数位不超过8位,小数点不超过2位",
      },
    ],
    projectDetails: {
      configEditTitle: "编辑参数",
      configLabel: [
        "远程服务次数(次)",
        "现场故障服务(次)",
        "现场维保服务(次)",
        "现场故障完成次数(次)",
        "现场维保完成次数(次)",
        "允许超限功率时间阈值(h)",
        "允许超合同功率时间阈值(h)",
        "启动电瓶跌落最大电压限制(V)",
        "启动成功最长时间限制(S)",
      ],
      configForm: [
        "远程服务次数",
        "现场故障服务次数",
        "现场维保服务次数",
        "现场故障完成次数",
        "现场维保完成次数",
        "允许超限功率时间阈值",
        "允许超合同功率时间阈值",
        "启动电瓶跌落最大电压限制",
        "启动成功最长时间限制",
      ],
      configFormPlaceholder: [
        "请输入远程服务次数",
        "请输入现场故障服务次数",
        "请输入现场维保服务次数",
        "请输入现场故障完成次数",
        "请输入现场维保完成次数",
        "请输入允许超限功率时间",
        "请输入允许超合同功率时间",
        "请输入启动电瓶跌落最大电压",
        "请输入启动成功最长时间",
      ],
      configFormRules: [
        "仅可输入不超过四位数的整数",
        "限制整数位不超过3位,小数点不超过1位",
      ],
      configFormTip: ["Times"],
      contract: {
        operate: "Upload file",
        title: "Upload contract file",
        form: ["File type", "File upload", "File name", "备注"],
        formPlaceholder: [
          "请选择文件类型",
          "请选择文件",
          "请输入文件名称",
          "请输入备注",
        ],
        formTip: ["The length cannot exceed 15 characters"],
        fileTip: [
          "选取文件",
          "(支持不超过10M的.doc、docx、xls、xlsx、pdf、rar、zip、jpg、jpge、png文件；最多上传10个文件)",
          "A maximum of three files can be uploaded",
          "上传文件格式有误!",
          "Upload file size cannot exceed 10MB!",
          "File upload successful!",
          "File upload failed, please resubmit!",
        ],
        showFile: "合同文件查看",
        showFileLabel: [
          "File type",
          "File name",
          "Document remarks",
          "File list",
        ],
        deleteFileTip: [
          "Delete file",
          "Are you sure to delete the current file?",
          "Deleted file successfully!",
          "Failed to delete the file, please try again!",
        ],
      },
      contractColumns: [
        "File type",
        "File name",
        "Upload time",
        "uplink",
        "备注",
      ],
      fileListColumns: ["File name", "File size"],
      personnel: {
        operate: ["Add personnel", "Editorial staff"],
        userType: ["商务", "Technology", "Group onitoring user"],
        tip: [
          "添加用户成功!",
          "Failed to add user, please resubmit!",
          "编辑用户成功!",
          "Edit user failed, please resubmit!",
          "Deletion of personnel",
          "Are you sure to delete the current project staff?",
          "Personnel deleted successfully!",
          "Failed to delete personnel, please try again!",
        ],
      },
      personnelColumns: [
        "Type of company",
        "Company name",
        "Personnel type",
        "Person in charge",
        "Person in charge telephone",
      ],
      personnelFormPlaceholder: [
        "Please select a company type",
        "Please select Company",
        "Please select a person type",
        "Please select responsible person",
      ],
      genset: {
        operate: [
          "添加机组",
          "维保策略",
          "Electronic fence",
          "Controller configuration",
          "Project progress",
          "Modified fence",
        ],
        type: ["Configured", "Unconfigured", "Enabled", "Unenabled"],
        title: [
          "添加机组",
          "All selectable units",
          "Selected units",
          "移除机组",
        ],
        label: ["Unit location", "Engine model", "功率"],
        labelPlaceholder: [
          "Please select unit location",
          "Input engine model",
          "Minimum power",
          "Maximum power",
        ],
        tip: [
          "Adding a group succeeded!",
          "Failed to add the group, please resubmit!",
          "Unit removal successful!",
          "Failed to remove the unit, please try again!",
          "Are you sure to remove Unit XX from the current project?",
        ],
        drawerTab: ["Genset configuration"],
        electronicFence: {
          title: ["Modify the electronic fence Settings"],
          label: ["Fence center", "Fence radius"],
          labelPlaceholder: [
            "Please input the center longitude",
            "Please input the center latitude",
            "Please input the fence radius",
          ],
          tip: [
            "Turn off the electronic fence",
            "Are you sure to close the current unit electronic fence?",
          ],
        },
      },
      crewColumns: [
        "Unit name",
        "Logo",
        "Engine model",
        "Run time",
        "Unit location",
        "Main/Standby",
        "Contract power",
        "Limited power",
        "Rated power",
        "Standby power",
        "Synchronization/No",
        "Gen-set configuration",
      ],
      selectCrewColumns: [
        "Unit name",
        "Logo",
        "Engine model",
        "功率",
        "Run time",
        "Unit location",
      ],
      parallel: {
        operate: ["new", "relieve", "Add as host", "Add as extension"],
        title: [
          "Adding and combining unit",
          "Editing and combining unit",
          "Current project all units",
          "Current parallel unit",
          "Parallel main engine",
          "Parallel generator",
        ],
        label: ["Unit location", "Engine model", "功率", "Current total power"],
        labelPlaceholder: [
          "Please select unit location",
          "Input engine model",
          "Minimum power",
          "Maximum power",
        ],
        tip: [
          "Only one host can be set up in the parallel group!",
          "And the unit must set up a host!",
          "The parallel unit must set up an extension!",
          "Add and combine group successfully!",
          "Failed to add and combine the group, please resubmit!",
          "Edit and set successful!",
          "Failed to edit and combine the group, please resubmit!",
          "Successful deactivation!",
          "Deactivating parallel failed, please try again!",
          "Are you sure to cancel the current parallel?",
          "After the cancellation, the relevant parallel will be changed to the 'single unit' status and still exist in this project.",
        ],
      },
      parallelColumns: [
        "Host name",
        "Extension name",
        "Genset Number",
        "Combined unit total power",
      ],
      setParallelCrewColumns: [
        "Unit name",
        "Logo",
        "Engine model",
        "功率",
        "Run time",
      ],
      group: {
        operate: [
          "New group",
          "Supervisory control",
          "details",
          "Confirm deletion",
          "Confirm save",
        ],
        title: [
          "Group details",
          "New unit group",
          "Editing group",
          "Please select non-group units",
          "Unit group information",
        ],
        label: ["Group name", "Group remarks", "机组数量", "Total rated power"],
        tip: [
          "Support unit name/logo/engine type keyword search",
          "功率",
          "XX units have been added",
          "Do you want to delete it?",
          "Please fill in the group name",
          "Please select at least one unit",
        ],
      },
      groupColumns: [
        "Group name",
        "机组数量",
        "总额定功率(kW)",
        "备注",
        "Update time",
        "Update person",
      ],
      setGroupCrewColumns: [
        "Unit name and identification",
        "Logo",
        "Engine model",
        "Rated Power(kW)",
        "Synchronization/No",
        "Run time",
      ],
    },
    progressManage: {
      operate: [
        "Project schedule management",
        "Associated unit",
        "Next",
        "Previous",
        "Return list",
      ],
      title: [
        "Project progress",
        "Single machine project progress record",
        "Project progress record view",
        "Project unit engineering progress (overall)",
        "Progress record",
        "Project progress record",
        "Project progress record added",
        "Project progress record editing",
        "Step 1: Associate the units",
        "Step 2: Improve the record content",
      ],
      label: ["Currently selected"],
      tip: [
        "Delete record",
        "Are you sure to delete the current record? '",
        "Delete record successfully! '",
        "Failed to delete the record, please try again!",
      ],
      eventTypeEnum: ["Project start-up", "End of project"],
      projectProgressColumns: [
        "Event type",
        "Event content",
        "Last edit time",
        "operator",
        "Total number of records",
      ],
      projectProgressRecordsColumns: [
        "Event type",
        "Event content",
        "Associated unit",
        "Last edit time",
        "operator",
      ],
      progressRecordsColumns: [
        "Unit name",
        "Logo",
        "Event type",
        "Event content",
        "Number of event records",
      ],
      gensetRalatedColumns: [
        "Unit name",
        "Logo",
        "Engine model",
        "功率",
        "Run time",
        "Power limiting",
        "Synchronization/No",
      ],
      crewInfoColumns: [
        "Unit name",
        "Logo",
        "Engine model",
        "功率",
        "Run time",
        "Unit location",
        "Power limiting",
        "Synchronization/No",
        "Electronic fence open condition",
        "Maintenance policy input status",
      ],
      gensetProgressColumns: [
        "Event type",
        "Event content",
        "Last edit time",
        "operator",
        "Number of records per unit",
      ],
      gensetProgressRecordsColumns: [
        "Event type",
        "Event content",
        "Last edit time",
        "operator",
      ],
      sheetFormLabel: { "01": ["项目编号", "工程部人员"] },
    },
    completionRecord: {
      title: [
        "Expense detail",
        "Expense summary",
        "Completion report",
        "Operation report",
        "Customer satisfaction",
        "View picture",
      ],
      expensesOperate: [
        "append",
        "EDITOR",
        "Click to view",
        "Upload report",
        "reupload",
      ],
      expensesForm: [
        "Expenditure type",
        "Item of expenditure",
        "Project amount",
        "Instructions",
        "picture",
      ],
      expensesFormPlaceholder: [
        "Please select an expense type",
        "Please select expenses",
        "Please enter the item amount",
        "Please enter a description of expenses",
        "请选择文件",
      ],
      typeEnum: ["Income", "expenditure"],
      expensesTip: [
        "No more than 50 words",
        "Limit integers to no more than 8 digits and decimal points to no more than 2 digits",
        "(Only.jpg/jpge/png image files up to 5M are supported; Upload up to 3 pictures)",
        "添加开支项目成功!",
        "Failed to add expense item, please resubmit!",
        "编辑开支项目成功!",
        "Edit expense item failed, please resubmit!",
        "Delete expenditure items",
        "Are you sure to delete current expenses?",
        "删除开支项目成功!",
        "Failed to delete expense item, please resubmit!",
      ],
      expensesStatistics: [
        "Total project revenue",
        "Total project expenditure",
      ],
      costManageColumns: [
        "Expenditure type",
        "Item of expenditure",
        "Project amount",
        "Instructions",
        "picture",
        "modifier",
        "Modification time",
      ],
      costAggregationColumns: [
        "Expenditure type",
        "Item of expenditure",
        "Total project amount",
        "Number of items",
      ],
      completionReportColumns: [
        "Completion report",
        "Completion status",
        "modifier",
        "Modification time",
      ],
      completionEnum: ["To be completed", "Done"],
      customerSatisfactionColumns: [
        "Customer satisfaction",
        "Completion status",
        "modifier",
        "Modification time",
      ],
      operationReportColumns: [
        "Operation report",
        "Completion status",
        "uplink",
        "Upload time",
      ],
      tips: [
        "文件类型错误!",
        "Upload file size cannot exceed 30MB!",
        "上传报告成功!",
        "重新上传报告成功!",
        "Processing",
      ],
    },
    report: {
      title: ["Power generating calculation"],
      label: [
        "Power supply unit",
        "Cumulative running time",
        "Cumulative power generation",
        "Total power generation",
      ],
      typeOpt: [
        "This month",
        "last week",
        "first half of the month",
        "last month",
      ],
    },
    monitor: {
      title: ["Monitoring overview", "Spare parts inventory"],
      time: [
        "项目开始时间",
        "项目结束时间",
        "Current date",
        "XX days from the end of the project",
      ],
      power: [
        "Contract power",
        "Limited power",
        "Rated power",
        "Standby power",
        "Realtime power",
      ],
      gensetData: [
        "Run",
        "报警",
        "Warning",
        "Stop",
        "Offline",
        "Genset Number",
        "Number of parallel machines",
        "Number of units",
        "Total number of closing",
        "Number of main stations",
        "Number of spare units",
        "实时报警",
        "Fault repair",
        "Maintenance & inspection",
        "Units requiring operation and maintenance in the next 30 days",
        "Maintenance point inspection",
        "Communication expiration",
        "Next automatic maintenance time",
      ],
      parametersTitle: [
        "Reliability index",
        "Unit life index",
        "Labor cost index",
        "Economic index",
        "Item parameter",
      ],
      parametersItem: {
        0: [
          "Power supply failure times",
          "Number of equipment failures",
          "超限制功率时间(h)",
          "启动电瓶电压跌落(V)",
          "启动成功时间(S)",
          "",
        ],
        1: [
          "最大负荷强度(%)",
          "The number of times the power limit is exceeded",
          "项目平均负荷(kW)",
          "维保完成率(%)",
          "High water temperature alarm times",
          "",
        ],
        2: [
          "云服务替代率(%)",
          "Number of remote service failures",
          "Maintain the number of remote services",
          "现场故障服务次数",
          "现场维保服务次数",
          "",
        ],
        3: [
          "项目燃油能耗(g/kW·h)",
          "项目总燃油用量(L)",
          "项目燃气能耗(m³/kW·h)",
          "项目总燃气用量(m³)",
          "项目总发电量(kW·h)",
          "超合同功率时间(h)",
        ],
        4: [
          "允许超限功率时间阈值(h)",
          "允许超合同功率时间阈值(h)",
          "启动电瓶跌落最大电压限制(V)",
          "启动成功最长时间限制(S)",
        ],
      },
      genset: {
        title: [
          "单机组",
          "Realtime power",
          "Limited power",
          "并机组",
          "Number of parallel machines",
          "总实时功率",
          "总限制功率",
          "Tips: After moving the mouse to the lower parallel area, hold down the keyboard shift key and scroll down the mouse wheel to see more parallel units",
        ],
        status: ["Offline", "Stop", "Warning", "报警", "Run"],
        typeLabel: ["Diesel engine", "Gas engine"],
        reliabilityLabel: ["Main unit", "Standby unit"],
        unitLife: [
          "Breaking-in period",
          "Health period",
          "Aging period",
          "Life extension",
        ],
        gateOpen: ["Switching on", "switching"],
        expireLabel: [
          "Communication expires after XX days",
          "It has expired XX days",
          "No communication period",
        ],
        canUse: ["usable", "Not available"],
        alertList: [
          "Warning",
          "Stop",
          "Click to enter the unit monitoring page",
          "Click to enter the maintenance monitoring page",
          "Current real-time alarm",
        ],
        maintenanceList: [
          "维保",
          "当前维保提醒",
          "Click to enter the maintenance monitoring page",
        ],
        offlineInfo: [
          "Off-line message",
          "Off-line time",
          "Communication due date",
          "Last battery voltage",
          "Final signal strength",
          "使用流量",
          "总流量",
          "Final positioning",
        ],
        dataItem: {
          0: "Cumulative operation",
          1: "Cooling water temperature",
          2: "Generating capacity",
          3: "Oil pressure",
          4: "Fuel level",
          5: "Oil level",
          6: "Oil Temperature",
          7: "Battery voltage",
          8: [
            "Cylinder 1",
            "Cylinder 2",
            "Cylinder 3",
            "Cylinder 4",
            "Cylinder 5",
            "Cylinder 6",
          ],
          9: [
            "Intake pressure",
            "Air intake temperature",
            "Intake manifold pressure",
            "Intake manifold temperature",
            "Exhaust port temperature",
            "Exhaust oxygen",
            "Throttle opening",
            "Turbine pressure",
          ],
          10: [
            "Throttle actuator",
            "Throttle position",
            "PTO status",
            "ECU status",
            "Range of revolutions requested",
            "Requested torque range",
          ],
          11: [
            "Real-time load rate",
            "Load intensity",
            "Average load",
            "有功冲击负荷强度",
            "Reactive impact load intensity",
            "Overpower running time",
            "Low load operation time",
            "High load operation time",
          ],
          12: [
            "Generating frequency",
            "Phase voltage",
            "Line voltage",
            "Electric current",
          ],
          13: [
            "GOV output percentage",
            "AVR output percentage",
            "Frequency difference",
            "Voltage difference",
            "Phase difference",
          ],
          14: ["Gas consumption", "Gas energy consumption"],
          15: ["Fuel consumption", "Fuel consumption"],
          16: ["Ambient temperature", "Altitude", "Atmospheric pressure"],
          operate: [
            "See more",
            "Expand to see more",
            "Pack up",
            "日运维图",
            "周运维图",
            "运维图",
            "Genset monitoring",
            "维保监控",
          ],
        },
      },
      group: {
        selectLabel: [
          "Switch group",
          "Select group",
          "project list",
          "List of groups",
        ],
        tips: [
          "请选择项目",
          "Please select Group",
          "Failed to get item list information, please check the network!",
          "Failed to obtain the group list information, please check the network!",
        ],
        label: [
          "Genset Number",
          "Run",
          "报警",
          "Warning",
          "Offline",
          "Stop",
          "Switching on",
          "总实时功率",
          "Total rated power",
        ],
      },
      failure: {
        title: ["Number of equipment failures", "Power supply failure times"],
        equipmentSearchLabel: [
          "Supports search by keyword for fault description or confirmation person",
          "Failure time",
          "Processing result",
        ],
        operateLabel: [
          "Add a power supply fault record",
          "Fault details",
          "Added power supply fault information",
          "Edit power supply fault information",
          "View details about power supply faults",
        ],
        formLabel: [
          "Power supply fault Description",
          "Power supply fault time",
          "Troubleshooting result",
          "Fault confirmation person",
          "备注",
        ],
        tip: [
          "XX records have been selected",
          "Do you want to delete this record?",
        ],
      },
    },
  },
  equipmentManagement: {
    searchList: ["Filter", "type"],
    searchListPlaceholder: ["to", "Start time", "End time", "请选择"],
    columnsLabelList: ["索引值", "Test type", "创建时间", "View curve"],
    dateErrorTip: "Make sure the end date is after the start date",
    mouldPage: {
      listLabelList: [
        "Genset information",
        "Genset configuration",
        "运行监控",
        "维保监控",
        "电能质量监控",
        "Degradation Analysis",
        "Remote unlock",
        "Send Cloud message",
        "Genset report",
      ],
      dateRefreshTips: [
        "The data is updated every 3 seconds",
        "Data last updated",
        "机组浏览足迹",
      ],
      subInfoList: [
        "Generator set number",
        "Engine model",
        "Rated power",
        "限功功率",
        "Cumulative running time",
        "当前位置",
      ],
      unitBrowsingFootprint: {
        title: "机组浏览足迹",
        tip: "If you log out of the account or clear the browser cache, the browsing footprint will be cleared",
        noData: "No record yet!",
      },
    },
    crewConfig: {
      controllerConfiguration: "Controller configuration",
      configList: [
        "Power limiting calibration",
        "Reliability calibration",
        "Maintenance configuration",
        "Data reset",
      ],
      beforeSaveTip: "Are you sure to write data to the controller?",
      powerLimitForm: {
        list: [
          "机组长时限制功率",
          "机组长时限制时间（24h）",
          "开启限功率进风阻力大上限",
          "进风阻力大限制功率（KW）",
          "开启限功率环境温度高上限",
          "Ambient temperature High Limited power (KW)",
          "Turn on the upper limit of power limit water temperature",
          "High water temperature Limited power (KW)",
          "Enable the power limit altitude upper limit",
          "Altitude limited power (KW)",
          "High ambient temperature limit power warning threshold",
          "High water temperature limits the power warning threshold",
          "High altitude limit power 1 Alert threshold",
          "High altitude limit power 2 Alert threshold",
          "High inlet resistance limits power delay",
          "Ambient temperature limits power delay",
          "High water temperature limits power delay",
          "High altitude limits power delay",
        ],
        conditionList: [
          "while",
          "机组长时",
          "时限制功率",
          "进风阻力",
          "and",
          "延迟",
          "Ambient temperature",
          "时进行提醒",
          "Tank temperature",
        ],
        statusTextList: ["writing", "reading", "Read failure", "Write failure"],
        precisionTextList: [
          "Reserved integer",
          "Keep one decimal place",
          "Keep two decimal places",
        ],
      },
      strategyConfigForm: {
        strategyConfig: "Configure maintenance policies",
        baseConfig: "Basic configuration",
        maintenanceItems: "Maintenance matters",
        useTemplate: "Reference template",
        runTimeList: [
          "Run time (actual/policy)",
          "Absolute duration (practical/strategic)",
        ],
        queryErrorTip: "Query failed!",
        messageList: ["请添加维保事项!", "维保事项不允许保存空值!"],
        deleteTipList: ["删除维保事项", "确认删除数据吗？"],
      },
    },
    crewinfo: {
      crewStatusList: ["Offline", "Stop", "Warning", "Fault", "Run"],
      allCrew: "全部机组",
      columnsList: [
        "Unit name",
        "Genset status",
        "Installation site",
        "Longitude and latitude",
      ],
      searchList: ["机组编码搜索", "Unit location screening"],
      searchListPlaceholder: [
        "请输入机组编码",
        "Please select the location of the unit",
      ],
      operateButtonList: ["Genset information", "Genset report"],
      dataList: [
        {
          title: "基本信息",
          options: [
            {
              options: [
                "机组名称",
                "云猫标识",
                "经度",
                "纬度",
                "安装地点",
                "曲线",
                "有人值守",
              ],
            },
          ],
        },
        {
          title: "机组信息",
          options: [
            {
              options: [
                "出厂编号",
                "品牌",
                "型号",
                "规格",
                "生产厂家",
                "生产日期",
                "备注",
              ],
            },
            {
              options: [
                "额定转速(r/min)",
                "额定频率(Hz)",
                "额定电流(A)",
                "额定功率(kW)",
                "额定电压(V)",
                "视在功率(kVA)",
                "功率因数",
              ],
            },
            { options: ["机组照片"] },
          ],
        },
        {
          title: "维保信息",
          options: [
            {
              options: [
                "客户编号",
                "客户公司",
                "设备归属公司",
                "设备责任人",
                "责任人联系电话",
                "维保公司",
                "维保联系人",
                "联系人电话",
              ],
            },
          ],
        },
        {
          title: "控制器信息",
          options: [
            {
              options: [
                "出厂编号",
                "品牌",
                "型号",
                "规格",
                "生产厂家",
                "生产日期",
              ],
            },
            { options: ["控制器类型", "是否可以控制", "供电系统"] },
            {
              type: "ol",
              key: "ProgrammableSensors",
              options: ["可编程传感器 1", "可编程传感器 2", "可编程传感器 3"],
            },
          ],
        },
        {
          title: "发动机信息",
          options: [
            {
              options: [
                "出厂编号",
                "品牌",
                "型号",
                "规格",
                "生产厂家",
                "生产日期",
              ],
            },
          ],
        },
        {
          title: "发电机信息",
          options: [
            {
              options: [
                "出厂编号",
                "品牌",
                "型号",
                "规格",
                "生产厂家",
                "生产日期",
              ],
            },
          ],
        },
        {
          title: "采集器信息",
          options: [
            {
              options: [
                "出厂编号",
                "品牌",
                "型号",
                "规格",
                "生产厂家",
                "生产日期",
                "通讯协议状态",
                "通讯说明",
              ],
            },
          ],
        },
        {
          title: "易耗配件材料统计",
          options: [
            {
              options: [
                "巡检卡号",
                "防冻液容量",
                "机油容量",
                "空气滤清器型号",
                "个数",
                "机油滤清器型号",
                "个数",
                "机油旁滤清器型号",
                "个数",
                "柴油滤清器型号",
                "个数",
              ],
            },
          ],
        },
        {
          title: "基站信息",
          options: [{ options: ["基站名称", "基站编号", "基站地点"] }],
        },
      ],
      tabsList: ["Genset information", "Genset Resume", "Genset Part"],
      sensorsProgrammable: ["Programmable sensor", "Name"],
      formatData: [
        "AMF Module",
        "1P2W",
        "3P3W",
        "Done",
        "To be sent",
        "sending",
        "communication normal",
      ],
      dialog: {
        title: ["Add Resume", "Edit Resume", "Add Genset Part"],
        label: ["Content", "File upload", "选取文件"],
      },
      keyPartsItemList: [
        "Genset Part",
        "Mfg N.O",
        "Brand",
        "Model",
        "Specification",
        "厂商",
      ],
    },
    crewReport: {
      tabsList: [
        "Factory Test Report",
        "Delivery Test Report",
        "Starting Eeliability Report",
        "Power Time Matrix Report",
        "Run Report",
        "Operational Reliability Report",
      ],
      reportCommonTableColumnList: [
        "索引值",
        "Test type",
        "创建时间",
        "Examine Report",
        "delete",
      ],
      timeMatrixReport: {
        sourceDescribe: [
          "Data sources",
          "Acquire gen-set Info",
          "Manual input",
        ],
        title: "Matrix analysis report of power time",
        tableItemList: ["3-D matrix", "2-D matrix"],
        descriptionsItems: [
          "Engine serial No.",
          "Engine model",
          "Engine brand",
          "Engine ECU model",
          "Alternator serial No.",
          "Alternator model",
          "Alternator brand",
          "AVR model",
          "Controller serial No.",
          "Controller model",
          "Controller brand",
          "Cloud module Logo",
          "Rated speed",
          "Rated power",
          "Rated Frequency",
          "Apparent Power",
          "Rated Voltage",
          "Rated Current",
          "Power Factor",
          "Limited power",
          "Ambient temperature",
          "Atmospheric pressure",
          "Altitude",
          "Testing time",
        ],
        downloadTitle: "Matrix analysis report of power time",
      },
      crewOperateReportTitle: "Genset Run report",
      crewReliabilityReportTitle: "Genset Operational Reliability Report",
      crewOperateRecordItems: [
        "Unit name",
        "Cloud module Logo",
        "Brand",
        "Mfg N.O",
        "Engine",
        "Generator",
        "Collector",
        "Controller",
        "Cumulative power generation",
        "Cumulative running time",
      ],
      echartsItems: [
        "Generating capacity",
        "Run time",
        "Times",
        "Shutdown Alarm",
        "Warning Alarm",
        "Times",
      ],
      startingReliabilityReport: {
        reportTitle: "Tendency analysis report of gen-set starting reliability",
        echartsItems: [
          "Battery Voltage",
          "Water Temperature",
          "Water Temperature",
          "Fuel level",
          "Battery 1 Start Voltage Drop",
          "Battery 2 Start Voltage Drop",
          "Start Success Time",
        ],
        yAxisItems: [
          "Battery Voltage",
          "Water Temperature",
          "Water Temperature",
          "Fuel level",
          "Timestamp",
        ],
      },
    },
    crewDistribute: {
      tabsList: ["地图模式", "架构模式"],
      searchList: ["Unit name", "Genset status", "Company name"],
      searchListPlaceholder: [
        "请输入机组名称",
        "Please select the unit status",
        "Please enter the company name",
      ],
      mchStateOpt: [
        "All",
        "在线",
        "Fault",
        "Warning",
        "Run",
        "Stop",
        "Offline",
      ],
    },
    crewMonitor: {
      lastCollectTime: "Last sampling time",
      latestRunRecord: "Latest running record",
      openFullscreen: "Full screen",
      realTimeAlert: "实时报警",
      control: {
        title: "Control",
        list: ["Stop", "Mannual", "Auto", "Reset", "Start"],
        handleControl: [
          "Are you sure to press this button",
          "Operation prompt",
          "确定",
          "Cancel",
          "已取消",
        ],
      },
      crewPic: "Gen-set picture",
      crewVideo: "Gen-set video",
      durationWithoutPowerGeneration: "Period of continuous non generation",
      allMobileData: "Total Flow (Month)",
      usedMobileData: "Used Flow",
      powerOnTimes: "Start times",
      powerTotal: "Power generating calculation",
      fullscreenTitle: "Full screen",
      currentTime: "Current time",
      settingTitle: "监控设置",
      scrollTitle: "滚动",
      intervalTitle: "间隔",
      statusTitle: "状态",
      searchListPlaceholder: ["Input Generator Name"],
      crewListLabels: "Genset List",
      crewLocationLabels: "GPS",
      fuelOilCurve: "燃油曲线",
    },
    crewLocation: {
      fence: "Electronic fence",
      fenceStatus: ["Open", "Turn off"],
      fenceModify: "edit",
      backToOrigin: "Return to the current position of the unit",
      setFence: "Set up electronic fence",
      setFenceCurrent: "Current radius",
      closeFenceTip: "Are you sure to close the electronic fence?",
    },
    crewTrace: {
      noTraceTip:
        "There is no record of position movement of the generator set",
      searchErrorTip:
        "The start date must be before the end time! Please check.",
    },
    crewOperateRecord: {
      columnsLabelList: ["type", "operator", "Operating time"],
    },
    runningRecord: {
      columnsLabelList: [
        "Unit name",
        "Start time",
        "End time",
        "duration",
        "发电kWh",
      ],
    },
    alertHistory: {
      dialogTitle: "View log curve",
      dialog: ["Unit name", "Alarm time", "Alarm name"],
      columns: ["内容", "type", "Start time", "End time"],
      operateLabel: "View log curve",
      typeOpt: ["All", "Warning", "Stop"],
    },
    onlineRecord: {
      columns: ["Unit name", "type", "时间"],
      typeOpt: ["All", "Offline", "上线"],
    },
    generationEnergyStatistics: {
      typeOpt: [
        "This month",
        "last week",
        "first half of the month",
        "last month",
      ],
      tableLabelList: [
        "Power generating calculation",
        "Unit name",
        "Start time",
        "End time",
        "Cumulative power generation",
        "Cumulative running time",
      ],
      tooltip: ["日累计发电量", "日累计运行时间"],
    },
    historicCurve: {
      expandLabelList: ["unfold", "Pack up"],
      typeOpt: [
        "All",
        "First 2 hours",
        "First 1.5 hours",
        "First hour",
        "First 0.5 hours",
      ],
    },
  },
  settingManagement: {
    maintenanceStrategy: {
      maintenanceItems: "Maintenance matters",
      maintenanceNew: "Maintenance Strategy (New)",
      searchList: [
        "Name of the maintenance policy",
        "Engine brand",
        "Policy main/standby category",
        "Maintenance policy status",
      ],
      columnsList: [
        "Name of the maintenance policy",
        "Engine brand",
        "Engine series",
        "Policy main/standby category",
        "Strategy active and standby status",
        "The final editor",
        "Last edit time",
      ],
      dropdownModelList: ["All", "上柴", "潍柴", "玉柴"],
      dropdownStrategyTypeList: ["Stand-by unit", "Host unit"],
      beforeSaveTip:
        "The changes you made may not have been saved. Are you sure to return?",
      newAddFormLabelList: [
        "Time",
        "Number",
        "Time",
        "Number",
        "Time",
        "维保节拍个数",
      ],
    },
    advertisement: {
      nameList: ["Small program", "Home carousel pictures"],
      formLabelList: [
        "Type of picture",
        "Name of picture",
        "Upload pictures",
        "URL",
        "备注",
      ],
      newAddButtonLabel: "新增图片",
      columnsList: [
        "Name of picture",
        "Type of picture",
        "thumbnail",
        "sort",
        "URL",
        "备注",
        "状态",
        "operator",
        "Last modification time",
        "id",
      ],
      errorTip: " 请上传宽/高比例为2:1且小于5M的图片！",
    },
  },
  operation: {
    operationChart: {
      tableLabelList: [
        "Basic information",
        "项目信息",
        "Genset information",
        "Configuration information",
        "项目编号",
        "Project name",
        "Engine model",
        "Alternator model",
        "Standby power",
        "Rated power",
        "Item type",
        "Project time",
        "Controller model",
        "Rated speed",
        "Rated Current",
        "项目地址",
        "Rated Frequency",
        "Rated Voltage",
        "Number of starts",
        "Altitude",
        "Ambient temperature",
        "Atmospheric pressure",
        "运行报警",
        "Click to jump to the alert page",
        "Maintenance alarm",
        "weather",
        "Maintenance cycle",
        "Unit operation information",
        "Cumulative running time",
        "Generating capacity",
        "平均负荷强度",
      ],
      expandLabelList: ["Pack up", "unfold"],
    },
    chart: {
      timeInterval: "时间间隔",
      timeList: [
        "1分钟",
        "5分钟",
        "10分钟",
        "30分钟",
        "1小时",
        "2小时",
        "4小时",
      ],
    },
    operationalChartDaily: {
      title: "单日运维图报告",
      noProject: "No record",
      projectNoGenset: "This project does not bind the unit!",
      pleaseSelectGenset: "Please select the unit!",
      fourPower: ["Contract power", "限功功率", "Rated power", "Standby power"],
      chartList: {
        title: [
          "Unit operation law",
          "Start-up reliability",
          "Maintenance beat",
          "Matching power",
        ],
        describe: [
          "通过了解机组规律可以猜测客户工作时间规律，进行维保节拍、沟通等时间确认。",
          "通过观察环境温度、气压信息，来评估对机组设备的启动影响。",
          "查看油耗和进风过滤阻力对燃油、过滤器进行维保节拍了解。",
          "了解某天内功率各个时段有功功率、无功功率情况，用于合同，限功、额定、备用等功率匹配。",
        ],
        tips: [
          [
            "通过发电有功功率展示该当前机组在一天中各个时间的工作情况，从而了解客户每天的用电情况，用电高峰期、用户稳定期等。",
            "有功功率：单位KW。",
          ],
          null,
          [
            "进风过滤阻力：用于查看环境恶劣程度，通过查看阻力大小判断是否需要清洗滤网，如：阻力增大到88Pa，则需要进行清洗。",
            "油耗：用于预测加油，通过观察油耗使用情况，可了解在一天何时进行加油处理。",
          ],
          [
            "查看客户负载情况，知晓客户负载使用情况，为客户精准匹配功率段，可以为超出合同功率部分提供收费证明。",
            "合同功率(w1)：租赁项目立项时与客户约定的使用功率。",
            "限功功率(w2)：设定机组在一个合理的功率范围内进行发电运行，以防超功率运行损坏装备。",
            "额定功率(w3)：机组出厂的额定功率。",
            "备用功率(w4)：机组可以达到的最大功率值。",
            "有功功率：有功功率是指单位时间内实际发出或消耗的交流电能量，是周期内的平均功率。查看有功负载情况。",
            "无功功率：客户设备端电动机负载情况。",
          ],
        ],
        dataItems: [
          ["有功功率", "发动机转速"],
          ["环境温度", "水温"],
          ["油耗", "进风过滤阻力"],
          ["有功功率", "无功功率", "谐波分析总谐波畸变率"],
        ],
        yAxisItems: [
          ["有功功率", "发动机转速"],
          ["环境温度/水温"],
          ["油耗", "进风过滤阻力"],
          ["有功功率", "谐波分析总谐波畸变率"],
        ],
      },
      rulesList: [
        "Please enter the product name",
        "Please enter the product number",
        "Please enter contact person",
        "Please enter a contact number",
        "Please enter the service address",
      ],
      searchList: ["项目", "机组", "日期"],
      buttonLabelList: [
        "Alarm curve recording",
        "One click repair record",
        "Start curve recording",
        "Instantaneous curve",
        "Click skip page",
        "Send Cloud message",
        "click One-click Repair",
        "One-click Repair",
        "Are you sure to initiate a request for parameter adjustment?",
        "Remote configuration",
        "Service Application",
      ],
      repairForm: [
        "Service Application",
        "Repair Product",
        "Mfg N.O",
        "Contact",
        "Contact Number",
        "Service Address",
        "Fault Picture",
        "Fault Description",
        "Preview",
      ],
      curveOpt: [
        "Water jacket battery voltage",
        "Water jacket heater AC line voltage",
        "Jacket heater current",
        "Jacket heater water temperature",
        "ECU inlet air temperature",
        "ECU communication status",
        "ECU turbine pressure",
        "ECU fuel consumption speed",
        "Fuel depletion sensor %",
        "Oil Temperature",
        "Fuel tank capacity",
        "Capacity of the tank to be filtered",
        "Fill fuel tank capacity",
        "Liquid waste tank capacity",
        "Seat fuel tank level",
        "Liquid level of the tank to be filtered",
        "Fill the oil tank level",
        "Drain the oil sensor liquid level",
        "Fuel oil and gas separator liquid level",
        "Liquid waste tank level",
        "U-pan oil level",
        "Intake air filtration resistance",
        "Ambient temperature",
        "Battery 1 voltage",
        "Charger voltage",
        "Floating charge current",
        "Fuel level",
        "Oil pressure",
        "Water Temperature",
        "Engine speed",
        "Reactive Power",
        "Active Power",
        "Generating phase current",
        "Generating frequency",
        "Generator phase voltage",
        "Generating line voltage",
        "Mains Power Factor",
        "Mains Reactive Power",
        "Mains Active Power",
        "Mains frequency",
        "Mains Wire Voltage",
        "Mains Phase Voltage",
        "APF communication status",
        "Speed Fluctuation Rate",
        "Power fluctuation",
        "Motor bearing temperature",
        "U-phase winding temperature",
        "W phase winding temperature",
        "V phase winding temperature",
      ],
      totalDataObj: [
        "Total refueling times of generator set",
        "Cumulative fuel consumption of generator set",
        "Cumulative running time of generator set",
        "Cumulative generating capacity of generator set",
        "Cumulative MTBF of the generator set",
        "Cumulative overpower time of generator set",
        "Cumulative average energy consumption of units",
        "Cumulative low load operation time of generator set",
        "Cumulative high load running time of the generator set",
      ],
      chart: {
        title: "日运维图",
        yAxis: [
          "Power factor, ECU communication status",
          "Battery Voltage",
          "Water temperature, liquid level",
          "Three-phase current",
          "Three-phase voltage",
          "Oil pressure",
        ],
      },
    },
    operationalChartWeekly: {
      title: "周运维图报告",
      buttonLabelList: [
        "Click to jump to the project maintenance policy configuration page",
        "Configure maintenance policies",
      ],
      recordList: [
        "Equipment alarm record",
        "Maintenance prompt records",
        "Environmental risk warning",
        "Event time",
        "Alarm name",
      ],
      reliability: [
        "Start-up reliability trend",
        "The startup reliability is judged and observed by the battery voltage drop and startup success time.",
      ],
      errorTip2: "Operation failed, please check the network!",
      chartList: {
        title: ["Customer work pattern", "Load law", "Optimization strategy"],
        describe: [
          "通过了解客户规律可以猜测客户工作时间规律，进行维保节拍、沟通等时间确认。",
          "通过有功功率和无功功率指标数据，展示最近7天负载情况。",
          "查看油耗和进风过滤阻力对燃油、过滤器进行维保策略优化。",
        ],
        tips: [
          [
            "通过发电有功功率以及发电量展示当前机组在各个时间的工作情况，从而了解客户每天的用电情况，用电高峰期、用户稳定期等。",
            "有功功率：在单位时间内，最大有功功率值，单位kW。",
            "发电量：在单位时间内，累计的总发电量，单位：kW·h。",
            "注：在客户工作规律图表中，因取的是最大有功功率，发电量在该图表中不等于有功功率 * 时间。",
          ],
          [
            "查看客户负载情况，知晓客户负载使用情况，为客户精准匹配功率段，可以为超出合同功率部分提供收费证明。",
            "合同功率(w1)：租赁项目立项时与客户约定的使用功率。",
            "限功功率(w2)：设定机组在一个合理的功率范围内进行发电运行，以防超功率运行损坏装备。",
            "额定功率(w3)：机组出厂的额定功率。",
            "备用功率(w4)：机组可以达到的最大功率值。",
            "有功功率：有功功率是指单位时间内实际发出或消耗的交流电能量，是周期内的平均功率。查看有功负载情况。",
            "无功功率：客户设备端电动机负载情况。",
          ],
          [
            "通过查看油耗、进风过滤阻力、燃油含水量等指标信息，观察一周的变化情况，可用于优化维保策略。",
            "进风过滤阻力：用于查看环境恶心劣程度，通过查看阻力大小判断是否需要清洗滤网，如：阻力增大到88Pa，则需要进行清洗。",
            "油耗：用于预测加油，通过观察油耗使用情况，可了解在一天何时进行加油处理。",
            "燃油含水量：燃油中含水占比。",
          ],
        ],
        dataItems: [
          ["有功功率", "发电量"],
          ["有功功率", "无功功率"],
          ["油耗", "进风过滤阻力", "燃油含水量"],
        ],
        yAxisItems: [
          ["有功功率", "发电量"],
          ["有功功率", "无功功率"],
          ["油耗", "%"],
        ],
      },
      reliabilityChart: ["时长", "Battery voltage", "电压最低值", "启动时长"],
    },
    gensetLock: {
      title: ["Genset information", "机组解锁机", "解锁机记录"],
      operateButton: ["锁机", "解锁"],
      gensetInfoList: [
        "Unit name",
        "Cloud module Logo",
        "Engine model",
        "Alternator model",
        "Controller brand",
        "Controller model",
      ],
      tableList: ["type"],
      columnsList: [
        "Genset Name",
        "type",
        "Operating time",
        "operator",
        "内容",
      ],
      dialog: {
        tip: [
          "Are you sure you want to unlock remotely?",
          "Are you sure you want to lock the machine remotely?",
          "Caution:The device won't be able to start again if the remote lock operated.",
          "Locking Reason",
          "Characters length does not exceed 200",
        ],
      },
    },
    cloudMessagePush: {
      addButtonLabel: "Add content",
      attentions: "The controller does not support the function.",
      columnsList: [
        "Genset Name",
        "Edit Message",
        "Broadcast period",
        "Issue time",
        "type",
      ],
      typeList: ["Send", "Clear"],
      dialog: {
        columnsList: [
          "Unit name",
          "Cloud module Logo",
          "type",
          "Select message template",
          "Edit Message",
          "Broadcast period",
        ],
        attentions: 'Replacing message template "---"',
        attentions2:
          '\n\nBroadcasting no stop if the  "Broadcast period" is set to "0"or left blank.\n\n\n\n',
      },
      mouldList: [
        "Technical Support Hot-line",
        "Gen-set running well,pay the balance!",
        "The warranty period has expired,pay the balance!",
        "WARNING!No money no honey",
        "REMINDER:Device has unknown running under risky,pls contact Technical Support Hot-line",
        "REMINDER:Pay rent,if not gen-set is not working.",
        "REMINDER:Xh left for maintenance,pls contact Technical Support Hot-line",
        "Technical Support Hot-line",
        "Technical Support Hot-line",
        "Technical Support Hot-line",
        "REMINDER:Add antifreeze",
        "REMINDER:Add coolant",
        "REMINDER:Oil pressure high,change oil and oli filter",
        "REMINDER:Oil pressure,add oil",
        "REMINDER:Examine battery",
        "Others",
      ],
    },
    feedback: {
      people: "Feedback person",
      classification: "Work order classification",
      classificationStatus: "Work order status",
      confirm: {
        title: "Close work order",
        tip: "Are you sure to close the current ticket?",
        successMes: "Closing the work order succeeded",
        errorMes: "Failed to close the ticket. Please try again",
      },
      detailTitle: "工单详情",
      detailList: [
        "Work order number",
        "Contact Number",
        "Affiliated enterprise",
        "No more than 100 characters",
        "Please enter a reply message!",
        "Upload at least one picture!",
        "Confirm sending?",
        "Data submission, please wait...",
      ],
      formTip: [
        "Upload only",
        "picture（s）",
        "Upload file size cannot exceed 5MB!",
      ],
    },
    remoteTuning: {
      list: {
        searchFormPlaceholder: [
          "Input Generator Name",
          "Please enter the customer name",
        ],
        option1: ["To be confirmed", "Confirmed", "Done", "Reviewed"],
        option2: ["Unmanned", "Guarded"],
        operate: ["Confirm", "Configuration", "Historical record"],
        columns: [
          "Service order number",
          "Applicant",
          "Application time",
          "Unit name",
          "Customer  name",
          "Customer contact",
          "状态",
          "dispatcher",
          "Whether the parameter can be adjusted",
          "Unit coding",
        ],
        tips: ["Are you sure?", "Do you want to delete it?"],
      },
      history: {
        infoLabel: [
          "Unit name",
          "Cloud module Logo",
          "Controller brand",
          "Confuguration protocol",
          "Installation site",
          "Communication protocol",
          "Guarded",
        ],
        columns: ["Name", "Old value", "New value", "unit", "Update time"],
      },
      operation: {
        operate: ["Complete service"],
        tabList: ["Parameters", "Function", "Curve Data", "measure", "维保"],
      },
    },
    deteriorationAnalysis: {
      tabList: [
        "Degradation Analysis-Engine water tank",
        "Degradation Analysis-",
        "Degradation Analysis-",
      ],
      timeLabel: ["today", "This week", "This month", "This year"],
      dataLabel: ["Diagnostic index", "Deterioration index"],
    },
    leaseGenset: {
      searchForm: [
        "Generator set number",
        "Running state",
        "Lease status",
        "Unit location screening",
        "Lease type",
      ],
      searchFormPlaceholder: [
        "Please enter the unit number",
        "Please select the running status",
        "Please select lease status",
        "Please select the location of the unit",
        "Please select a lease type",
      ],
      runStatusEnum: ["Offline", "Stop", "Risky", "Fault", "Run"],
      leaseStatusEnum: [
        "For Rent",
        "Renting",
        "Repair",
        "Construct",
        "Maintenance",
      ],
      leaseTypeEnum: ["运维", "Managed operation and maintenance"],
      columns: [
        "Genset Name",
        "Logo",
        "Engine model",
        "功率",
        "Run time",
        "Lease type",
        "Lease status",
        "Running state",
        "Unit location",
        "Number of leases",
      ],
      selectCrewColumns: ["Genset Name", "Logo", "Unit location", "Lease type"],
      addTitle: [
        "添加机组",
        "Optional unit",
        "Selected units",
        "Editing generator set",
      ],
      addSearchForm: ["Genset Name", "Logo", "Unit location"],
      addSearchFormPlaceholder: [
        "Please enter the device name",
        "Please enter identification",
        "Please select unit location",
      ],
      tips: [
        "Adding a group succeeded!",
        "Failed to add the group, please resubmit!",
        "编辑机组成功!",
        "编辑机组失败，请重新提交!",
        "移除机组",
        "Are you sure to remove the current unit?",
        "Unit removal successful!",
        "Failed to remove the unit, please try again!",
      ],
    },
    maintenanceMonitor: {
      title: [
        "Alarm message",
        "Intelligent maintenance records",
        "Service Application",
        "Maintenance policy details",
        "Generator set image",
        "Gen-set picture",
        "Gen-set video",
        "Fuel unit",
        "Cooling water unit",
        "Oil unit",
        "Liquid waste tank unit",
      ],
      specialLabel: "自动补换机油周期情况",
      operate: ["Open", "Close", "Fuel unit"],
      monitorItem: {
        0: ["Cooling water unit", "Oil unit", "Liquid waste tank unit"],
        1: ["Automatic oil refill cycle", "Fuel presupply"],
        2: [
          "Fuel depletion sensor",
          "Fuel tank allowance",
          "Fuel refill",
          "Fuel extraction pump",
        ],
        3: [
          "Cooling level",
          "Current water temperature",
          "A-phase current",
          "B-phase current",
          "C-phase current",
          "AC line voltage",
          "Water temperature heating",
          "Jacket heater",
          "Water tank refill",
        ],
        4: ["Engine oil pan level"],
        5: [
          "Replenishment of fuel tank allowance",
          "Oil pan replenishment",
          "Oil refill pump",
          "New fuel tank replenishment",
          "Extractor external oil pump",
        ],
        6: [
          "Residual amount of tank to be filtered",
          "Oil pan discharge",
          "Waiting tank pump",
          "Waste oil tank discharge",
          "Waste oil pump",
        ],
        7: ["Liquid waste tank level"],
      },
      tips: [
        "No camera",
        "Switch to maintenance view",
        "Switch to card view",
        "Switch to emulation view",
        "Record key data before and after intelligent maintenance",
      ],
      stepTitles: [
        "",
        "Resting state",
        "readiness",
        "Test fueling status",
        "Test the fueling stand",
        "Test the pumping status",
        "Test the suction stand",
        "Official fueling condition",
        "Official pumping status",
      ],
      IMRDialogLabel: ["Maintenance time"],
      IMRDialogColumns: [
        "Start time",
        "End time",
        "Cooling water unit",
        "Automatic oil refill cycle",
        "Fuel surplus",
        "Oil pan oil level",
        "New fuel tank allowance",
        "New fuel tank %",
        "Remaining tank of filter",
        "To filter oil tank %",
        "Waste liquid tank allowance",
        "Waste liquid tank %",
        "Battery voltage",
      ],
      dealDialogLabel: [
        "Real-time monitoring transaction registration",
        "Processing registration",
        "Processing record",
        "Select a processed real-time monitoring event",
        "remarks",
        "transaction",
      ],
      dealDialogOperate: ["Confirmation of registration"],
      simulationView: {
        0: [
          "Tank level",
          "Water Temperature",
          "Water temperature heating",
          "Jacket heater",
          "Water tank refill",
        ],
        1: ["Intake line level", "Fuel presupply"],
        2: [
          "Body temperature",
          "进风阻力",
          "Feed surplus",
          "Oil pan oil level",
          "Battery voltage",
          "Liquid waste tank",
        ],
        3: ["Percentage drainage", "Oil unit", "Liquid waste tank unit"],
        4: [
          "Replenishment tank",
          "Oil pan replenishment",
          "Oil refill pump",
          "New fuel tank replenishment",
          "Extractor external oil pump",
        ],
        5: [
          "Waiting tank",
          "油底壳抽油",
          "Waiting tank pump",
          "Waste oil tank discharge",
          "Waste oil pump",
        ],
        6: ["Base fuel tank", "Fuel refill", "Fuel extraction pump"],
        title: "Maintain the simulation view",
        status: ["Normal", "Lack of water", "Containing water"],
      },
      maintenanceView: {
        status: ["状态", "Start", "stop"],
        label_0: ["Maintain workstation enable signal status"],
        label_1: ["Manual mode", "Automatic mode"],
        label_2: [
          "抽新机油泵",
          "油底壳机油",
          "补机油箱还能抽",
          "油底壳机油还能补",
        ],
        label_3: [
          "Waste oil pump",
          "Waiting tank",
          "油底壳机油还能排",
          "待滤油箱还能排",
        ],
        label_4: ["排水泵", "Liquid waste tank", "排水百分比还能排"],
        label_5: ["外部补新机油泵", "Replenishment tank", "补机油箱还能补"],
        label_6: ["外部排废机油泵", "Waiting tank", "待滤油箱还能排"],
        label_7: ["外部抽燃油泵", "Base fuel tank", "底座燃油还能补"],
      },
    },
    powerQuality: {
      label: [
        "实时数据",
        "历史曲线",
        "APF启动按钮",
        "APF停止按钮",
        "APF复位按钮",
      ],
      statusLabel: [
        "系统初始化",
        "系统停止",
        "电压爬升",
        "等待带载",
        "Normal operation",
      ],
      typeOpt: [
        "First 2 hours",
        "First 1.5 hours",
        "First hour",
        "First 0.5 hours",
      ],
      searchLabel: [
        "Time span",
        "unfold",
        "Pack up",
        "select all.",
        "Parameter selection",
        "未查询到相关数据,建议修改查询条件",
      ],
      apfParamsGroupList: {
        item_0: {
          typeName: "发电机侧",
          props: [
            "电源侧A相电流畸变率",
            "电源侧B相电流畸变率",
            "电源侧C相电流畸变率",
            "",
            "电源侧A相电压",
            "电源侧B相电压",
            "电源侧C相电压",
            "",
            "电源侧A相电流",
            "电源侧B相电流",
            "电源侧C相电流",
            "",
            "电源侧A相功率因数",
            "电源侧B相功率因数",
            "电源侧C相功率因数",
            "",
            "电源侧总功率因数",
            null,
            "电源侧电流负序不平衡度",
            "电源侧电流零序不平衡度",
            "",
            "Motor bearing temperature",
            "U-phase winding temperature",
            "V phase winding temperature",
            "W phase winding temperature",
          ],
        },
        item_1: {
          typeName: "负荷侧",
          props: [
            "负荷侧A相电流畸变率",
            "负荷侧B相电流畸变率",
            "负荷侧C相电流畸变率",
            "负荷侧A相电流",
            "负荷侧B相电流",
            "负荷侧C相电流",
            "负荷侧A相功率因数",
            "负荷侧B相功率因数",
            "负荷侧C相功率因数",
            "负载侧总功率因数",
            "负载侧电流负序不平衡度",
            "负载侧电流零序不平衡度",
          ],
        },
        item_2: {
          typeName: "GPQC电能质量控制器",
          props: [
            "Harmonic analysis Total harmonic distortion rate",
            "谐波分析基波分量",
            "谐波分析直流分量",
            "",
            "直流总电压",
            "直流电压1",
            "直流电压2",
            "",
            "滤波器A相直流电流",
            "滤波器B相直流电流",
            "滤波器C相直流电流",
            "滤波器N相直流电流",
            "IGBT1温度",
            "IGBT2温度",
            "IGBT3温度",
            "内部温度",
          ],
        },
      },
      paramsOptionsList: [
        "机组谐波含量",
        "Harmonic analysis Total harmonic distortion rate",
        "谐波分析基波分量",
        "谐波分析直流分量",
        "APF-IGBT3温度",
        "APF-IGBT2温度",
        "APF-IGBT1温度",
        "APF内部温度",
        "APF滤波器N相电流",
        "APF滤波器三相直流电流",
        "APF三相直流电压",
        "APF负载侧三相电流畸变率",
        "APF负载侧三相电流",
        "APF电源侧三相电流畸变率",
        "APF电源侧线电压",
        "APF电源侧相电压",
        "APF communication status",
        "APF负载电流零序不平衡度",
        "APF负载电流负序不平衡度",
        "Motor bearing temperature",
        "U-phase winding temperature",
        "W phase winding temperature",
        "V phase winding temperature",
        "APF电源A相功率因数",
        "APF电源B相功率因数",
        "APF电源C相功率因数",
        "APF电源总功率因数",
        "APF负载A相功率因数",
        "APF负载B相功率因数",
        "APF负载C相功率因数",
        "APF负载总功率因数",
        "平均功率因数",
        "Reactive Power",
        "Active Power",
        "APF市电电流零序不平衡度",
        "APF市电电流负序不平衡度",
        "APF电源侧A相电流",
        "APF电源侧B相电流",
        "APF电源侧C相电流",
      ],
      tips: ["是否确定点击该控制按钮?", "Submission, please wait..."],
    },
  },
};
